[package]
name = "day_13"
version = "0.0.0"
edition = "2021"

[dependencies]
utils = { path = "../utils" }
eyre = { workspace = true }
pretty_assertions = { workspace = true }
colored = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
