[package]
name = "day_16"
version = "0.0.0"
edition = "2021"

[dependencies]
utils = { path = "../utils" }
eyre = { workspace = true }
pretty_assertions = { workspace = true }
colored = { workspace = true }
nom = { workspace = true }
itertools = "0.10.5"
