[workspace]
members = ["*/"]
exclude = ["target"]

[workspace.dependencies]
eyre = "0.6.8"
regex = "1"
pretty_assertions = "1.3.0"
nom = "7"
colored = "2"
priority-queue = "1.3.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
derive_more = "0.99.17"
