[package]
name = "day_14"
version = "0.0.0"
edition = "2021"

[dependencies]
utils = { path = "../utils" }
eyre = { workspace = true }
pretty_assertions = { workspace = true }
colored = { workspace = true }
nom = { workspace = true }
nom-supreme = "0.8.0"
